# This workflow calls an org-level reusable workflow for incrementing LCP and NPM package versions.

name: LCP Version Bump

on:
  workflow_dispatch:
    inputs:
      version_level:
        description: 'Version level to bump'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  call-bump-version-tag:
    uses: massif-press/.github/.github/workflows/bump-version-tag.yml@master
    with:
      version_level: ${{ inputs.version_level }}